export default {
  keyLabel: [
    { name: "DateTime", label: "日期时间" },
    { name: "PreClosePx", label: "昨收价" },
    { name: "OpenPx", label: "开盘价" },
    { name: "HighPx", label: "最高价" },
    { name: "LowPx", label: "最低价" },
    { name: "LastPx", label: "最新价" },
    { name: "NumTrades", label: "成交笔数" },
    { name: "InstrumentStatus", label: "交易状态" },
    { name: "TotalVolumeTrade", label: "成交总量" },
    { name: "TotalAmountTrade", label: "成交总金额" },
    { name: "TotalBidQty", label: "委托买入总量" },
    { name: "TotalOfferQty", label: "委托卖出总量" },
    { name: "WeightedAvgBidPx", label: "加权平均委买价格（债券共用）" },
    { name: "WeightedAvgOfferPx", label: "加权平均委卖价格（债券共用）" },
    { name: "WithdrawBuyNumber", label: "买入撤单笔数" },
    { name: "WithdrawSellNumber", label: "卖出撤单笔数" },
    { name: "WithdrawBuyAmount", label: "买入撤单数量" },
    { name: "WithdrawBuyMoney", label: "买入撤单金额" },
    { name: "WithdrawSellAmount", label: "卖出撤单数量" },
    { name: "WithdrawSellMoney", label: "卖出撤单金额" },
    { name: "TotalBidNumber", label: "买入总笔数" },
    { name: "TotalOfferNumber", label: "卖出总笔数" },
    { name: "BidTradeMaxDuration", label: "买入委托成交最大等待时间" },
    { name: "OfferTradeMaxDuration", label: "卖出委托成交最大等待时间" },
    { name: "NumBidOrders", label: "买方委托价位数" },
    { name: "NumOfferOrders", label: "卖方委托价位数" },
    { name: "BidPrice", label: "申买十价" },
    { name: "BidOrderQty", label: "申买十量" },
    { name: "BidNumOrders", label: "申买十实际总委托笔数" },
    { name: "BidOrders", label: "申买一前50笔订单" },
    { name: "OfferPrice", label: "申卖十价" },
    { name: "OfferOrderQty", label: "申卖十量" },
    { name: "OfferNumOrders", label: "申卖十实际总委托笔数" },
    { name: "OfferOrders", label: "申卖一前50笔订单" },
    { name: "IOPV", label: "ETF净值估值（ETF）" },
    { name: "ETFBuyNumber", label: "ETF申购笔数（ETF）" },
    { name: "ETFBuyAmount", label: "ETF申购数量（ETF）" },
    { name: "ETFBuyMoney", label: "ETF申购金额（ETF）" },
    { name: "ETFSellNumber", label: "ETF赎回笔数（ETF）" },
    { name: "ETFSellAmount", label: "ETF赎回数量（ETF）" },
    { name: "ETFSellMoney", label: "ETF赎回金额（ETF）" }
  ],
  keys: [
    "DateTime",
    "PreClosePx",
    "OpenPx",
    "HighPx",
    "LowPx",
    "LastPx",
    "NumTrades",
    "InstrumentStatus",
    "TotalVolumeTrade",
    "TotalAmountTrade",
    "TotalBidQty",
    "TotalOfferQty",
    "WeightedAvgBidPx",
    "WeightedAvgOfferPx",
    "WithdrawBuyNumber",
    "WithdrawSellNumber",
    "WithdrawBuyAmount",
    "WithdrawBuyMoney",
    "WithdrawSellAmount",
    "WithdrawSellMoney",
    "TotalBidNumber",
    "TotalOfferNumber",
    "BidTradeMaxDuration",
    "OfferTradeMaxDuration",
    "NumBidOrders",
    "NumOfferOrders",
    "BidPrice",
    "BidOrderQty",
    "BidNumOrders",
    "BidOrders",
    "OfferPrice",
    "OfferOrderQty",
    "OfferNumOrders",
    "OfferOrders",
    "IOPV",
    "ETFBuyNumber",
    "ETFBuyAmount",
    "ETFBuyMoney",
    "ETFSellNumber",
    "ETFSellAmount",
    "ETFSellMoney"
  ],
  dataStore: {
    DateTime: "",
    PreClosePx: "",
    OpenPx: "",
    HighPx: "",
    LowPx: "",
    LastPx: "",
    NumTrades: "",
    InstrumentStatus: "",
    TotalVolumeTrade: "",
    TotalAmountTrade: "",
    TotalBidQty: "",
    TotalOfferQty: "",
    WeightedAvgBidPx: "",
    WeightedAvgOfferPx: "",
    WithdrawBuyNumber: "",
    WithdrawSellNumber: "",
    WithdrawBuyAmount: "",
    WithdrawBuyMoney: "",
    WithdrawSellAmount: "",
    WithdrawSellMoney: "",
    TotalBidNumber: "",
    TotalOfferNumber: "",
    BidTradeMaxDuration: "",
    OfferTradeMaxDuration: "",
    NumBidOrders: "",
    NumOfferOrders: "",
    BidPrice: [],
    BidOrderQty: [],
    BidNumOrders: [],
    BidOrders: [],
    OfferPrice: [],
    OfferOrderQty: [],
    OfferNumOrders: [],
    OfferOrders: [],
    IOPV: "",
    ETFBuyNumber: "",
    ETFBuyAmount: "",
    ETFBuyMoney: "",
    ETFSellNumber: "",
    ETFSellAmount: "",
    ETFSellMoney: ""
  }
};
